sonar.projectKey=beto13_QuickOrderBack
sonar.organization=beto13

# Excluir migraciones EF y Razor Pages del análisis
sonar.exclusions=**/Migrations/**,**/Pages/**

# Excluir el proyecto de tests del coverage (solo medir el código productivo)
sonar.coverage.exclusions=**Tests*/**
